[book]
authors = ["Johannes Lötzsch"]
language = "de"
multilingual = false
src = "src"
title = "LF12"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
git-repository-url = "https://github.com/johannesloetzsch/LF11b/tree/main"
edit-url-template = "https://github.com/johannesloetzsch/LF11b/tree/main/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
